### ISSUE TITLE
`p`s in `Styles` tables are too small

### ISSUE THREAD

**Issue by Kiarokh** [jgroth/kompendium#70]
![image](https://user-images.githubusercontent.com/35954987/128159095-1e94a0a0-f3ad-476d-93ad-42355662f603.png)

````scss
.docs kompendium-markdown {
    display: block;
    width: calc(50% - 2rem);
}
````
